[package]
name = "termocast"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
dotenv = "0.15.0"
reqwest = "0.12.26"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
